[Exposed=Window]
interface HTMLScriptElement : HTMLElement {

    [Reflect, CEReactions] attribute DOMString src;
    [Reflect, CEReactions] attribute DOMString type;
    [Reflect=nomodule, CEReactions] attribute boolean noModule;
    [CEReactions] attribute boolean async;
    [Reflect, CEReactions] attribute boolean defer;
    [CEReactions] attribute DOMString text;
    [Reflect, CEReactions] attribute DOMString integrity;

    static boolean supports(DOMString type);

    [Reflect, CEReactions] attribute DOMString charset;
    [Reflect, CEReactions] attribute DOMString event;
    [Reflect=for, CEReactions] attribute DOMString htmlFor;

};
